"use strict";
exports.__esModule = true;
var Bag_1 = require("./bag/Bag");
var Passenger_1 = require("./human/passenger/Passenger");
var Person_1 = require("./human/Person");
var Meal_1 = require("./meal/Meal");
var Chef_1 = require("./human/staff/Chef");
var Flight_attendant_1 = require("./human/staff/Flight_attendant");
var Aeroplane_1 = require("./airline/Aeroplane");
var Seat_1 = require("./location/Seat");
var Route_1 = require("./Route");
var Flights_1 = require("./airline/Flights");
var Pilot_1 = require("./human/staff/Pilot");
var bag1 = new Bag_1.Bag("BA12");
var bag2 = new Bag_1.Bag("BA15");
var bag3 = new Bag_1.Bag("BA16");
var passenger1 = new Passenger_1.Passenger("Sreypheap", "Khin", 18, Person_1.Gender.FEMALE, bag1);
var passenger2 = new Passenger_1.Passenger("Sreyka", "Khun", 20, Person_1.Gender.FEMALE, bag2);
var passenger3 = new Passenger_1.Passenger("Sreyphin", "King", 20, Person_1.Gender.FEMALE, bag3);
var pilot1 = new Pilot_1.Pilot(15000, "bory", "jin", 30, Person_1.Gender.MALE);
var pilot2 = new Pilot_1.Pilot(15000, "chetra", "van", 35, Person_1.Gender.MALE);
var pilot3 = new Pilot_1.Pilot(15000, "vibol", "kim", 25, Person_1.Gender.MALE);
var meal1 = new Meal_1.Meal("Noodle", 12000);
var meal2 = new Meal_1.Meal("Pizza", 15000);
var meal3 = new Meal_1.Meal("Shop", 10000);
var chef1 = new Chef_1.Chef(800, "Da", "SA", 25, Person_1.Gender.FEMALE);
var chef2 = new Chef_1.Chef(800, "De", "SAN", 25, Person_1.Gender.FEMALE);
var chef3 = new Chef_1.Chef(800, "Den", "SIN", 25, Person_1.Gender.FEMALE);
var flight_attendant1 = new Flight_attendant_1.Flight_attendant(500, "Sophorn", "Hin", 90, Person_1.Gender.MALE);
var flight_attendant2 = new Flight_attendant_1.Flight_attendant(500, "Ah", "Yubin", 90, Person_1.Gender.MALE);
var flight_attendant3 = new Flight_attendant_1.Flight_attendant(500, "Sopana", "Pi", 90, Person_1.Gender.MALE);
var seat1 = new Seat_1.Seat("12V", 100, passenger1);
var seat2 = new Seat_1.Seat("25V", 100, passenger2);
var seat3 = new Seat_1.Seat("30V", 100, passenger3);
var aeroplane1 = new Aeroplane_1.Aeroplane("OH-LWP", seat1);
var aeroplane2 = new Aeroplane_1.Aeroplane("ZB1-HD", seat2);
var aeroplane3 = new Aeroplane_1.Aeroplane("WIN-WIN", seat3);
var route1 = new Route_1.Route("Phnom Penh", "Bangkok");
var route2 = new Route_1.Route("Bangkok", "Singapore");
var route3 = new Route_1.Route("Singapore", "UK");
var flight1 = new Flights_1.Flights("1/04/2023", "2/4/2023", "9:30am", "1:30pm", "M0120", route1, aeroplane1);
var flight2 = new Flights_1.Flights("13/04/2023", "13/4/2023", "9:30am", "1:30pm", "M0120", route2, aeroplane2);
var flight3 = new Flights_1.Flights("10/04/2023", "11/4/2023", "9:30am", "1:30pm", "M0120", route3, aeroplane3);
flight1.addChef(chef1);
flight1.addFlightAttendant(flight_attendant1);
flight1.addPerson(passenger1);
flight1.addPilot(pilot1);
console.log(flight1);
